# Copyright 2022 Google
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

#Build Flex Template
# TODO: set gs:// bucket to a local bucket
steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'build'
    args: ['install']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - dataflow
      - flex-template
      - build
      - gs://argolis-playground_dataflow/templates/dataflow-bigquery-to-jdbc.json
      - --image-gcr-path
      - gcr.io/$PROJECT_ID/dataflow-bigquery-to-jdbc:latest
      - --metadata-file
      - "metadata.json"
      - --sdk-language
      - JAVA
      - --flex-template-base-image
      - JAVA17
      - --jar
      - target/dataflow-bigquery-to-jdbc-0.1.0.jar
      - --env
      - FLEX_TEMPLATE_JAVA_MAIN_CLASS="com.mikenimer.swarm.bqToJdbc.StarterPipeline"
    waitFor: ['build']




